package com.java.project;

public enum Council {
	STATE_MEDICAL_COUNCILS,
	MEDICAL_COUNCIL_OF_INDIA,
	DENTAL_COUNCIL_OF_INDIA,
	CENTRAL_COUNCIL_OF_INDIAN_MEDICINE,
	CENTRAL_COUNCIL_OF_HOMEOPATHY;
	
	
}
